window.PHOTO_CREDITS={
 "h-a2-fontenay-cloitre": "Benjamin Smith · CC BY-SA 4.0 · Wikimedia Commons",
 "h-a2-fontenay-forge": "Myrabella · CC BY-SA 4.0 · Wikimedia Commons",
 "h-a3-manuscrit-caroline": "auteur inconnu · Public domain · Wikimedia Commons",
 "h-a4-vezelay-basilique": "PIERRE ANDRE LECLERCQ · CC BY-SA 4.0 · Wikimedia Commons",
 "h-a4-compostelle-cathedrale": "Antoine Cadotte · CC BY-SA 3.0 · Wikimedia Commons",
 "h-a6-palais-ducs-dijon": "Benjamin Smith · CC BY-SA 4.0 · Wikimedia Commons",
 "h-a6-puits-de-moise": "User:GO69 · CC BY-SA 4.0 · Wikimedia Commons",
 "h-a6-hospices-beaune": "Jebulon · Public domain · Wikimedia Commons",
 "h-b4-provins-remparts": "Pline · CC BY-SA 3.0 · Wikimedia Commons",
 "h-b4-provins-tour": "Xu Zhang · CC BY-SA 4.0 · Wikimedia Commons",
 "h-b5-moulin-eau": "Anne Desvignes · CC BY-SA 4.0 · Wikimedia Commons",
 "h-b5-four-pain": "Espandero · CC BY-SA 4.0 · Wikimedia Commons",
 "h-c1-puce-xenopsylla": "CDC/Dr. Pratt · Public domain · Wikimedia Commons",
 "h-c2-notre-dame-paris-facade": "Dietmar Rabich · CC BY-SA 4.0 · Wikimedia Commons",
 "h-c4-reims-cathedrale": "DXR · CC BY-SA 3.0 · Wikimedia Commons",
 "g-a3-terre-nasa": "NASA/Apollo 17 crew; taken by either Harrison Schmitt or Ron · Public domain · Wikimedia Commons",
 "g-a4-weltzeituhr": "Diego Delso · CC BY-SA 4.0 · Wikimedia Commons",
 "g-a4-terre-nuit": "NASA images by Reto Stöckli, based on data from NASA and NOA · Public domain · Wikimedia Commons",
 "g-a2-cassini": "Cassini, Cesar-Francois Julien, Roch-Joseph · Public domain · Wikimedia Commons",
 "g-a5-terre-espace": "NASA/Apollo 17 crew; taken by either Harrison Schmitt or Ron · Public domain · Wikimedia Commons",
 "g-a6-fuseaux-1507": "Martin Waldseemüller · Public domain · Wikimedia Commons",
 "g-a6-mercator-1569": "Gerardus Mercator · Public domain · Wikimedia Commons",
 "g-b2-mairie": "Elliott Brown from Birmingham, United Kingdom · CC BY-SA 2.0 · Wikimedia Commons",
 "g-b2-ter": "Benjamin Smith · CC BY-SA 4.0 · Wikimedia Commons",
 "g-b4-tgv-dijon": "MartinD · CC BY-SA 4.0 · Wikimedia Commons",
 "g-b4-tram-dijon": "Benjamin Smith · CC BY-SA 4.0 · Wikimedia Commons",
 "g-b6-source-seine": "Thesupermat · CC BY-SA 3.0 · Wikimedia Commons",
 "g-b6-canal-bourgogne": "Pierre André Leclercq · CC BY-SA 4.0 · Wikimedia Commons",
 "g-b6-morvan": "Own work · CC BY-SA 3.0 · Wikimedia Commons",
 "s-c1-nuages": "Jakec · CC BY-SA 4.0 · Wikimedia Commons",
 "s-c1-lac-kir": "Erkethan · CC BY-SA 3.0 · Wikimedia Commons",
 "s-c2-glacon": "Cleiton Andrade Andrade from Alfenas, Brasil · CC0 · Wikimedia Commons",
 "s-c2-ebullition": "James St. John · CC BY 2.0 · Wikimedia Commons",
 "s-c3-fleur-de-sel": "Romain Bréget · CC BY-SA 3.0 · Wikimedia Commons",
 "s-c4-station": "auteur inconnu · CC BY-SA 3.0 · Wikimedia Commons",
 "s-c5-iceberg": "IlyaHaykinson · CC BY 2.0 · Wikimedia Commons",
 "s-c5-cargo": "Petar Milošević · CC BY-SA 4.0 · Wikimedia Commons",
 "s-d1-montre": "Chetvorno · CC0 · Wikimedia Commons",
 "s-d2-brouette": "David Thomsen · CC BY-SA 4.0 · Wikimedia Commons",
 "s-d2-romaine": "Rama · CC BY-SA 2.0 fr · Wikimedia Commons",
 "s-d3-moufle": "auteur inconnu · CC0 · Wikimedia Commons",
 "s-d4-abri-meteo": "peter robinson · CC BY-SA 2.0 · Wikimedia Commons",
 "s-d5-girouette": "Globetrotter19 · CC BY-SA 3.0 · Wikimedia Commons",
 "s-d5-anemometre": "Unknown authorUnknown author · CC BY-SA 4.0 · Wikimedia Commons",
 "s-d6-tgv": "JLPC · CC BY-SA 3.0 · Wikimedia Commons",
 "s-e1-cadran-solaire": "Gzen92 · CC BY-SA 4.0 · Wikimedia Commons",
 "s-e2-dijon-ete": "Benjamin Smith · CC BY-SA 4.0 · Wikimedia Commons",
 "s-e3-eclipse-lune": "ESO/Y. Beletsky · CC BY 4.0 · Wikimedia Commons",
 "s-e4-sucre-dissolution": "Викидим · CC BY-SA 4.0 · Wikimedia Commons",
 "h-a1-baptistere-poitiers": "No machine-readable author provided. Rigolithe assumed (base · Public domain · Wikimedia Commons",
 "h-a1b-hospices-beaune": "Jebulon · Public domain · Wikimedia Commons",
 "h-a1c-vezelay-nef": "Benjamin Smith · CC BY-SA 4.0 · Wikimedia Commons",
 "h-b1-guedelon": "Benoît Prieur · CC0 · Wikimedia Commons",
 "h-b1-chateauneuf": "Christophe.Finot · CC BY-SA 2.5 · Wikimedia Commons",
 "h-b1b-berry-octobre": "Limbourg brothers / Barthélemy d'Eyck · Public domain · Wikimedia Commons",
 "g-a1-tram-dijon": "Chabe01 · CC BY-SA 4.0 · Wikimedia Commons",
 "g-a1-village-rural": "G CHP · CC BY-SA 2.5 · Wikimedia Commons",
 "g-b1-prefecture-dijon": "Erkethan · CC BY-SA 3.0 · Wikimedia Commons",
 "g-b1-hotel-ville-dijon": "Pline · CC BY-SA 3.0 · Wikimedia Commons",
 "s-a1b-abri-meteo": "peter robinson · CC BY-SA 2.0 · Wikimedia Commons",
 "s-a1b-anemometre": "Unknown authorUnknown author · CC BY-SA 4.0 · Wikimedia Commons",
 "s-a1b-pluviometre": "Jiří Sedláček · CC BY-SA 4.0 · Wikimedia Commons",
 "s-b1b-sucre-eau": "Викидим · CC BY-SA 4.0 · Wikimedia Commons",
 "s-b1c-tamis": "Bone, Muirhead, Sir, 1876-1953 · Public domain · Wikimedia Commons",
 "s-b1c-filtre-cafe": "Mateus S. Figueiredo · CC BY-SA 4.0 · Wikimedia Commons",
 "s-b1c-marais-salants": "Nono vlf · CC BY-SA 3.0 · Wikimedia Commons"
};
